# AprilTag configuration
april_tags:
  tag_0:
    id: 0
    position: [0.0, 0.0, 0.0]  # x, y, z in meters
    rotation: [0.0, 0.0, 0.0]  # roll, pitch, yaw in radians
  tag_1:
    id: 1
    position: [1.0, 0.0, 0.0]
    rotation: [0.0, 0.0, 0.0]
  tag_2:
    id: 2
    position: [1.0, 1.0, 0.0]
    rotation: [0.0, 0.0, 0.0]
  tag_3:
    id: 3
    position: [0.0, 1.0, 0.0]
    rotation: [0.0, 0.0, 0.0]

# Camera parameters
camera:
  width: 640
  height: 480
  matrix:  # Example camera matrix - should be calibrated for your camera
    - [1000.0, 0.0, 320.0]
    - [0.0, 1000.0, 240.0]
    - [0.0, 0.0, 1.0]
  distortion: [0.0, 0.0, 0.0, 0.0, 0.0]  # Example distortion coefficients 